services:
  {{PROJECT_NAME}}-celery-worker:
    build:
      context: .
      dockerfile: docker/Dockerfile.celery
    container_name: {{PROJECT_NAME}}-celery-worker
    working_dir: /workspace
    volumes:
      - ..:/workspace:cached
    command: celery -A {{PROJECT_NAME}} worker --loglevel=info
    depends_on:
      {{PROJECT_NAME}}-redis:
        condition: service_healthy
    environment:
      CELERY_BROKER_URL: redis://{{PROJECT_NAME}}-redis:6379/0
      CELERY_RESULT_BACKEND: redis://{{PROJECT_NAME}}-redis:6379/1

  {{PROJECT_NAME}}-celery-beat:
    build:
      context: .
      dockerfile: docker/Dockerfile.celery
    container_name: {{PROJECT_NAME}}-celery-beat
    working_dir: /workspace
    volumes:
      - ..:/workspace:cached
    command: celery -A {{PROJECT_NAME}} beat --loglevel=info
    depends_on:
      {{PROJECT_NAME}}-redis:
        condition: service_healthy
    environment:
      CELERY_BROKER_URL: redis://{{PROJECT_NAME}}-redis:6379/0
      CELERY_RESULT_BACKEND: redis://{{PROJECT_NAME}}-redis:6379/1
