services:
  tarnished:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    container_name: tarnished
    volumes:
      # Mount the project directory into the container
      - .:/workspace:cached
      # Persist bash history
      # - ~/.bash_history:/home/node/.bash_history:cached
      # Mount host's .gitconfig.local for user name/email
      # - ~/.gitconfig:/home/node/.gitconfig:cached
      # - ~/.gitconfig.local:/home/node/.gitconfig.local:cached
      # - ~/.ssh:/home/node/.ssh:cached

      # Mount host's workspace
      # - ~/work/input:/home/node/input:ro

      # Github Cli Settings
      - ~/.config/gh:/home/node/.config/gh:cached
      # ssh config and host_config
      
    working_dir: /workspace
    # Keep the container running
    command: sleep infinity
    #extra_hosts:
    #  - "host.docker.internal:host-gateway"