FROM mcr.microsoft.com/vscode/devcontainers/base:bookworm

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl vim git ssh sudo bash \
    ripgrep \
    ca-certificates \
    wget \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

{{DOCKERFILE_EXTRAS}}

SHELL ["/bin/bash", "-c"]

# Keep the container running
CMD ["sleep", "infinity"]
