FROM mcr.microsoft.com/vscode/devcontainers/base:bookworm

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl vim git ssh sudo bash \
    ripgrep \
    ca-certificates \
    wget \
    jq \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

SHELL ["/bin/bash", "-c"]

# Keep the container running
CMD ["sleep", "infinity"]
